/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "mmi_api_metrics_histograms.h"

#include <unordered_map>

#include "util_napi_error_codes.h"

namespace OHOS {
namespace MMI {
enum InputHistogramErrorIndex {
    MMI_HISTOGRAM_ERROR_INDEX_NONE,
    MMI_HISTOGRAM_ERROR_INDEX_PERMISSION_CHECK_ERROR,       // 201
    MMI_HISTOGRAM_ERROR_INDEX_USE_SYSAPI_ERROR,             // 202
    MMI_HISTOGRAM_ERROR_INDEX_PARAMETER_ERROR,              // 401
    MMI_HISTOGRAM_ERROR_INDEX_INPUT_DEVICE_NOT_SUPPORTED,   // 801
    MMI_HISTOGRAM_ERROR_INDEX_INPUT_SERVICE_EXCEPTION,      // 3800001
    MMI_HISTOGRAM_ERROR_INDEX_DEVICE_NOT_EXIST,             // 3900001
    MMI_HISTOGRAM_ERROR_INDEX_KEYBOARD_DEVICE_NOT_EXIST,    // 3900002
    MMI_HISTOGRAM_ERROR_INDEX_NON_INPUT_APPLICATION,        // 3900003
    MMI_HISTOGRAM_ERROR_INDEX_PRE_KEY_NOT_SUPPORTED,        // 4100001
    MMI_HISTOGRAM_ERROR_INDEX_INPUT_OCCUPIED_BY_SYSTEM,     // 4200002
    MMI_HISTOGRAM_ERROR_INDEX_INPUT_OCCUPIED_BY_OTHER,      // 4200003
    MMI_HISTOGRAM_ERROR_INDEX_CODE_STATE_ERROR,             // 4300001
    MMI_HISTOGRAM_ERROR_INDEX_CONTROLLER_DISPLAY_NOT_EXIST, // 4300002
    MMI_HISTOGRAM_ERROR_INDEX_WINDOW_ID_PERMISSION_DENIED,  // 26500001
    MMI_HISTOGRAM_ERROR_INDEX_MAX
};

namespace {
const std::unordered_map<int32_t, int32_t> ERROR_CODE_TO_HISTOGRAM_ERROR_INDEX {
    { COMMON_PERMISSION_CHECK_ERROR, MMI_HISTOGRAM_ERROR_INDEX_PERMISSION_CHECK_ERROR },
    { COMMON_USE_SYSAPI_ERROR, MMI_HISTOGRAM_ERROR_INDEX_USE_SYSAPI_ERROR },
    { COMMON_PARAMETER_ERROR, MMI_HISTOGRAM_ERROR_INDEX_PARAMETER_ERROR },
    { INPUT_DEVICE_NOT_SUPPORTED, MMI_HISTOGRAM_ERROR_INDEX_INPUT_DEVICE_NOT_SUPPORTED },
    { INPUT_SERVICE_EXCEPTION, MMI_HISTOGRAM_ERROR_INDEX_INPUT_SERVICE_EXCEPTION },
    { COMMON_DEVICE_NOT_EXIST, MMI_HISTOGRAM_ERROR_INDEX_DEVICE_NOT_EXIST },
    { COMMON_KEYBOARD_DEVICE_NOT_EXIST, MMI_HISTOGRAM_ERROR_INDEX_KEYBOARD_DEVICE_NOT_EXIST },
    { COMMON_NON_INPUT_APPLICATION, MMI_HISTOGRAM_ERROR_INDEX_NON_INPUT_APPLICATION },
    { PRE_KEY_NOT_SUPPORTED, MMI_HISTOGRAM_ERROR_INDEX_PRE_KEY_NOT_SUPPORTED },
    { INPUT_OCCUPIED_BY_SYSTEM, MMI_HISTOGRAM_ERROR_INDEX_INPUT_OCCUPIED_BY_SYSTEM },
    { INPUT_OCCUPIED_BY_OTHER, MMI_HISTOGRAM_ERROR_INDEX_INPUT_OCCUPIED_BY_OTHER },
    { ERROR_CODE_STATE_ERROR, MMI_HISTOGRAM_ERROR_INDEX_CODE_STATE_ERROR },
    { CONTROLLER_DISPLAY_NOT_EXIST, MMI_HISTOGRAM_ERROR_INDEX_CONTROLLER_DISPLAY_NOT_EXIST },
    { ERROR_WINDOW_ID_PERMISSION_DENIED, MMI_HISTOGRAM_ERROR_INDEX_WINDOW_ID_PERMISSION_DENIED },
};
} // namespace

void HistogramError(const char *name, int32_t errorCode)
{
    auto iter = ERROR_CODE_TO_HISTOGRAM_ERROR_INDEX.find(errorCode);
    if (iter != ERROR_CODE_TO_HISTOGRAM_ERROR_INDEX.cend()) {
        HISTOGRAM_ENUMERATION(name, iter->second, MMI_HISTOGRAM_ERROR_INDEX_MAX);
    }
}
} // namespace MMI
} // namespace OHOS
